runtime: python
env: flex
entrypoint: python main.py

runtime_config:
    python_version: 3

beta_settings:
  cloud_sql_instances: dalokal:europe-west3:myinstanceid

# instance_class: F2

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# handlers:
# - url: /static
#   static_dir: dalokal_website/static

# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto

env_variables:
  DB_PASSWORD: 'My2418SQL5765'
