runtime: python38 

instance_class: F2

handlers:
- url: /static
  static_dir: dalokal_website/static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: My2418SQL5765
  CLOUD_SQL_DATABASE_NAME: dalokalschema
  CLOUD_SQL_CONNECTION_NAME: dalokal:europe-west3:myinstanceid
