runtime: python38 

instance_class: F2

handlers:
- url: /static
  static_dir: dalokal_website/static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: DATABASE_PASSWORD
  CLOUD_SQL_DATABASE_NAME: dalokalschema
  CLOUD_SQL_CONNECTION_NAME: dalokal-website:europe-west3:sql-instance
