runtime: python
env: flex

runtime_config:
    python_version: 3

  
beta_settings:
  cloud_sql_instances: dalokal:europe-west3:myinstanceid=tcp:3306

instance_class: F2

handlers:
- url: /static
  static_dir: dalokal_website/static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
