runtime: python38 

instance_class: F2

handlers:
- url: /static
  static_dir: dalokal_website/static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/dalokal:europe-west3:myinstanceid;dbname=dalokalschema
  MYSQL_USER: root
  MYSQL_PASSWORD: 'My2418SQL5765'
